name: CI/CD GymPal Documentation Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Check for lock file
        id: check_lock
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "has_lock=true" >> $GITHUB_OUTPUT
          else
            echo "has_lock=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ${{ steps.check_lock.outputs.has_lock && 'pnpm' || '' }}

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install
          fi

      - name: Lint markdown files
        run: pnpm run lint || echo "Linting completed with warnings"

      - name: Validate markdown files
        run: pnpm run validate || echo "Validation completed with warnings"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo owner
        id: lower
        run: |
          echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set SHA tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      # Build and push Docker image to GitHub Container Registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.lower.outputs.owner }}/gympal-docs:${{ steps.vars.outputs.sha_short }}
            ghcr.io/${{ steps.lower.outputs.owner }}/gympal-docs:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          # cache-from: type=registry,ref=ghcr.io/${{ steps.lower.outputs.owner }}/gympal-docs:latest
          # cache-to: type=registry,ref=ghcr.io/${{ steps.lower.outputs.owner }}/gympal-docs:latest,mode=max
      
      # TODO: Uncomment this when the GitOps repo is ready (PTI-GymPalGitOps)
      # - name: Set up SSH for GitOps repo
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.GIT_DEPLOY_KEY }}

      # - name: Checkout GitOps repo via SSH
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ${{ steps.lower.outputs.owner }}/PTI-GymPalGitOps
      #     path: gitops
      #     ssh-key: ${{ secrets.GIT_DEPLOY_KEY }}

      # - name: Update image tag in GitOps repo
      #   run: |
      #     cd gitops/charts/gympal-docs

      #     # Install yq
      #     sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
      #     sudo chmod +x /usr/local/bin/yq

      #     # Update image tag
      #     yq -i '.image.tag = "${{ steps.vars.outputs.sha_short }}"' values.yaml

      #     # Commit and push
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"
      #     git add values.yaml
      #     git commit -m "Update gympal-docs image tag to ${{ steps.vars.outputs.sha_short }}"
      #     git push origin main

